version: '2'
services:
  auth:
    image: kiss_arch/auth:latest
    user: app
    environment:
    - NODE_ENV=production
    entrypoint:
      - /auth/node_modules/.bin/knex
      - seed:run
    external_links:
      - services_postgres_1
networks:
  default:
    external:
      name: services_net1
